# Prediction:

Random Forest might perfrom better than Logistic Regression becuase random forest is usaly good with complex data such as the one we have becuase it has lot of features.

In [55]:
import numpy as np
import pandas as pd
from pathlib import Path

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler

In [34]:
train_df = pd.read_csv(Path('Resources/2019loans.csv'))
test_df = pd.read_csv(Path('Resources/2020Q1loans.csv'))

In [35]:
train_df.head()

,Unnamed: 0,index,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,loan_status,pymnt_plan,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,57107,57107,13375.0,0.1797,483.34,MORTGAGE,223000.0,Not Verified,low_risk,n,...,100.0,50.0,0.0,0.0,577150.0,122018.0,32000.0,170200.0,N,N
1,141451,141451,21000.0,0.1308,478.68,MORTGAGE,123000.0,Source Verified,low_risk,n,...,85.0,33.3,0.0,0.0,132750.0,27896.0,15900.0,35398.0,N,N
2,321143,321143,20000.0,0.1240,448.95,MORTGAGE,197000.0,Source Verified,low_risk,n,...,85.7,33.3,0.0,0.0,628160.0,114043.0,22600.0,90340.0,N,N
3,11778,11778,3000.0,0.1240,100.22,RENT,45000.0,Not Verified,low_risk,n,...,100.0,16.7,1.0,0.0,42006.0,20761.0,19900.0,15406.0,N,N
4,169382,169382,30000.0,0.1612,1056.49,MORTGAGE,133000.0,Source Verified,low_risk,n,...,100.0,66.7,0.0,0.0,283248.0,109056.0,79500.0,58778.0,N,N

In [36]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12180 entries, 0 to 12179
Data columns (total 86 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Unnamed: 0                  12180 non-null  int64
 1   index                       12180 non-null  int64
 2   loan_amnt                   12180 non-null  float64
 3   int_rate                    12180 non-null  float64
 4   installment                 12180 non-null  float64
 5   home_ownership              12180 non-null  object
 6   annual_inc                  12180 non-null  float64
 7   verification_status         12180 non-null  object
 8   loan_status                 12180 non-null  object
 9   pymnt_plan                  12180 non-null  object
 10  dti                         12180 non-null  float64
 11  delinq_2yrs                 12180 non-null  float64
 12  inq_last_6mths              12180 non-null  float64
 13  open_acc                    12180 non-null  float64
 14  pub_rec                     12180 non-null  float64
 15  revol_bal                   12180 non-null  float64
 16  total_acc                   12180 non-null  float64
 17  initial_list_status         12180 non-null  object
 18  out_prncp                   12180 non-null  float64
 19  out_prncp_inv               12180 non-null  float64
 20  total_pymnt                 12180 non-null  float64
 21  total_pymnt_inv             12180 non-null  float64
 22  total_rec_prncp             12180 non-null  float64
 23  total_rec_int               12180 non-null  float64
 24  total_rec_late_fee          12180 non-null  float64
 25  recoveries                  12180 non-null  float64
 26  collection_recovery_fee     12180 non-null  float64
 27  last_pymnt_amnt             12180 non-null  float64
 28  collections_12_mths_ex_med  12180 non-null  float64
 29  policy_code                 12180 non-null  float64
 30  application_type            12180 non-null  object
 31  acc_now_delinq              12180 non-null  float64
 32  tot_coll_amt                12180 non-null  float64
 33  tot_cur_bal                 12180 non-null  float64
 34  open_acc_6m                 12180 non-null  float64
 35  open_act_il                 12180 non-null  float64
 36  open_il_12m                 12180 non-null  float64
 37  open_il_24m                 12180 non-null  float64
 38  mths_since_rcnt_il          12180 non-null  float64
 39  total_bal_il                12180 non-null  float64
 40  il_util                     12180 non-null  float64
 41  open_rv_12m                 12180 non-null  float64
 42  open_rv_24m                 12180 non-null  float64
 43  max_bal_bc                  12180 non-null  float64
 44  all_util                    12180 non-null  float64
 45  total_rev_hi_lim            12180 non-null  float64
 46  inq_fi                      12180 non-null  float64
 47  total_cu_tl                 12180 non-null  float64
 48  inq_last_12m                12180 non-null  float64
 49  acc_open_past_24mths        12180 non-null  float64
 50  avg_cur_bal                 12180 non-null  float64
 51  bc_open_to_buy              12180 non-null  float64
 52  bc_util                     12180 non-null  float64
 53  chargeoff_within_12_mths    12180 non-null  float64
 54  delinq_amnt                 12180 non-null  float64
 55  mo_sin_old_il_acct          12180 non-null  float64
 56  mo_sin_old_rev_tl_op        12180 non-null  float64
 57  mo_sin_rcnt_rev_tl_op       12180 non-null  float64
 58  mo_sin_rcnt_tl              12180 non-null  float64
 59  mort_acc                    12180 non-null  float64
 60  mths_since_recent_bc        12180 non-null  float64
 61  mths_since_recent_inq       12180 non-null  float64
 62  num_accts_ever_120_pd       12180 non-null  float64
 63  num_actv_bc_tl              12180 non-null  float64
 64  num_actv_rev_tl             12180 non-null  float64
 65  num_bc_sats                 12180 non-null  float64
 66  num_bc_tl                   12180 non-null  float64
 67  num_il_tl                   12180 non-null  float64
 68  num_op_rev_tl               12180 non-null  float64
 69  num_rev_accts               12180 non-null  float64
 70  num_rev_tl_bal_gt_0         12180 non-null  float64
 71  num_sats                    12180 non-null  float64
 72  num_tl_120dpd_2m            12180 non-null  float64
 73  num_tl_30dpd                12180 non-null  float64
 74  num_tl_90g_dpd_24m          12180 non-null  float64
 75  num_tl_op_past_12m          12180 non-null  float64
 76  pct_tl_nvr_dlq              12180 non-null  float64
 77  percent_bc_gt_75            12180 non-null  float64
 78  pub_rec_bankruptcies        12180 non-null  float64
 79  tax_liens                   12180 non-null  float64
 80  tot_hi_cred_lim             12180 non-null  float64
 81  total_bal_ex_mort           12180 non-null  float64
 82  total_bc_limit              12180 non-null  float64
 83  total_il_high_credit_limit  12180 non-null  float64
 84  hardship_flag               12180 non-null  object
 85  debt_settlement_flag        12180 non-null  object
dtypes: float64(76), int64(2), object(8)
memory usage: 8.0+ MB

In [37]:
test_df.head()

,Unnamed: 0,index,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,loan_status,pymnt_plan,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,67991,67991,40000.0,0.0819,814.70,MORTGAGE,140000.0,Not Verified,low_risk,n,...,97.7,0.0,0.0,0.0,527975.0,70914.0,74600.0,99475.0,N,N
1,25429,25429,6000.0,0.1524,208.70,RENT,55000.0,Not Verified,low_risk,n,...,66.7,0.0,0.0,0.0,34628.0,23460.0,5900.0,23628.0,N,N
2,38496,38496,3600.0,0.1695,128.27,RENT,42000.0,Not Verified,low_risk,n,...,100.0,0.0,0.0,0.0,23100.0,19183.0,7300.0,15000.0,N,N
3,19667,19667,20000.0,0.1524,478.33,RENT,100000.0,Not Verified,low_risk,n,...,100.0,50.0,0.0,0.0,56481.0,43817.0,13800.0,35981.0,N,N
4,37505,37505,3600.0,0.1240,120.27,RENT,50000.0,Not Verified,low_risk,n,...,100.0,25.0,0.0,0.0,45977.0,32448.0,21000.0,24977.0,N,N

In [38]:
test_df.dropna()

,Unnamed: 0,index,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,loan_status,pymnt_plan,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,67991,67991,40000.0,0.0819,814.70,MORTGAGE,140000.0,Not Verified,low_risk,n,...,97.7,0.0,0.0,0.0,527975.0,70914.0,74600.0,99475.0,N,N
1,25429,25429,6000.0,0.1524,208.70,RENT,55000.0,Not Verified,low_risk,n,...,66.7,0.0,0.0,0.0,34628.0,23460.0,5900.0,23628.0,N,N
2,38496,38496,3600.0,0.1695,128.27,RENT,42000.0,Not Verified,low_risk,n,...,100.0,0.0,0.0,0.0,23100.0,19183.0,7300.0,15000.0,N,N
3,19667,19667,20000.0,0.1524,478.33,RENT,100000.0,Not Verified,low_risk,n,...,100.0,50.0,0.0,0.0,56481.0,43817.0,13800.0,35981.0,N,N
4,37505,37505,3600.0,0.1240,120.27,RENT,50000.0,Not Verified,low_risk,n,...,100.0,25.0,0.0,0.0,45977.0,32448.0,21000.0,24977.0,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4697,77282,77282,30000.0,0.1240,673.42,RENT,140480.0,Source Verified,high_risk,n,...,100.0,28.6,0.0,0.0,159688.0,110873.0,48400.0,107388.0,N,N
4698,77291,77291,24000.0,0.0756,747.22,RENT,50000.0,Not Verified,high_risk,n,...,100.0,0.0,0.0,0.0,62375.0,18928.0,13300.0,30775.0,N,N
4699,77292,77292,10000.0,0.2305,387.36,RENT,33000.0,Verified,high_risk,n,...,100.0,0.0,0.0,0.0,43250.0,33022.0,8500.0,29550.0,N,N
4700,77297,77297,8000.0,0.1862,205.86,RENT,38000.0,Source Verified,high_risk,n,...,95.0,0.0,1.0,0.0,31357.0,19595.0,1500.0,9657.0,N,N
4701,77304,77304,30000.0,0.2055,1123.34,RENT,180000.0,Source Verified,high_risk,n,...,100.0,33.3,0.0,0.0,218686.0,209389.0,5600.0,209986.0,N,N

In [39]:
#convert target column to numeric

test_df["loan_status"] = test_df["loan_status"].map({'high_risk': 1, 'low_risk': 0})
train_df["loan_status"] = train_df["loan_status"].map({'high_risk': 1, 'low_risk': 0})

train_df['loan_status'].unique()

array([0, 1])

# Convert categorical data to numeric and separate target feature for training data

In [40]:
train_df2 = pd.get_dummies(train_df)

train_df2

,Unnamed: 0,index,loan_amnt,int_rate,installment,annual_inc,loan_status,dti,delinq_2yrs,inq_last_6mths,...,verification_status_Verified,pymnt_plan_n,initial_list_status_f,initial_list_status_w,application_type_Individual,application_type_Joint App,hardship_flag_N,hardship_flag_Y,debt_settlement_flag_N,debt_settlement_flag_Y
0,57107,57107,13375.0,0.1797,483.34,223000.0,0,29.99,0.0,0.0,...,0,1,0,1,1,0,1,0,1,0
1,141451,141451,21000.0,0.1308,478.68,123000.0,0,11.26,2.0,0.0,...,0,1,0,1,1,0,1,0,1,0
2,321143,321143,20000.0,0.1240,448.95,197000.0,0,11.28,0.0,0.0,...,0,1,0,1,1,0,1,0,1,0
3,11778,11778,3000.0,0.1240,100.22,45000.0,0,18.08,0.0,0.0,...,0,1,0,1,1,0,1,0,1,0
4,169382,169382,30000.0,0.1612,1056.49,133000.0,0,27.77,0.0,2.0,...,0,1,0,1,1,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12175,354912,354912,19975.0,0.2565,801.09,28000.0,1,28.42,0.0,0.0,...,0,1,0,1,1,0,1,0,1,0
12176,354944,354944,15000.0,0.1774,540.34,50000.0,1,23.43,4.0,0.0,...,1,1,0,1,1,0,1,0,1,0
12177,354973,354973,3600.0,0.1862,131.28,60000.0,1,28.80,0.0,1.0,...,0,1,0,1,1,0,1,0,1,0
12178,355002,355002,15000.0,0.0881,475.68,62000.0,1,11.44,0.0,0.0,...,0,1,0,1,0,1,1,0,1,0
12179,355307,355307,15000.0,0.1774,540.34,54080.0,1,21.66,1.0,1.0,...,0,1,1,0,1,0,1,0,1,0

# Convert categorical data to numeric and separate target feature for testing data

In [43]:
test_df2 = pd.get_dummies(test_df)

test_df2['debt_settlement_flag_Y'] = 0

test_df2.head()

,Unnamed: 0,index,loan_amnt,int_rate,installment,annual_inc,loan_status,dti,delinq_2yrs,inq_last_6mths,...,verification_status_Verified,pymnt_plan_n,initial_list_status_f,initial_list_status_w,application_type_Individual,application_type_Joint App,hardship_flag_N,hardship_flag_Y,debt_settlement_flag_N,debt_settlement_flag_Y
0,67991,67991,40000.0,0.0819,814.70,140000.0,0,19.75,0.0,1.0,...,0,1,0,1,1,0,1,0,1,0
1,25429,25429,6000.0,0.1524,208.70,55000.0,0,11.52,2.0,0.0,...,0,1,0,1,1,0,1,0,1,0
2,38496,38496,3600.0,0.1695,128.27,42000.0,0,6.74,0.0,0.0,...,0,1,0,1,1,0,1,0,1,0
3,19667,19667,20000.0,0.1524,478.33,100000.0,0,12.13,0.0,2.0,...,0,1,0,1,1,0,1,0,1,0
4,37505,37505,3600.0,0.1240,120.27,50000.0,0,16.08,0.0,3.0,...,0,1,0,1,1,0,1,0,1,0

In [44]:
y_train = train_df2['loan_status']
X_train = train_df2.drop(['loan_status'], axis=1) 
y_test = test_df2['loan_status']
X_test = test_df2.drop(['loan_status'], axis=1 )

In [45]:
print(X_train)
print(y_train)
print(X_test)
print(y_test)

       Unnamed: 0   index  loan_amnt  int_rate  installment  annual_inc  \
0           57107   57107    13375.0    0.1797       483.34    223000.0
1          141451  141451    21000.0    0.1308       478.68    123000.0
2          321143  321143    20000.0    0.1240       448.95    197000.0
3           11778   11778     3000.0    0.1240       100.22     45000.0
4          169382  169382    30000.0    0.1612      1056.49    133000.0
...           ...     ...        ...       ...          ...         ...
12175      354912  354912    19975.0    0.2565       801.09     28000.0
12176      354944  354944    15000.0    0.1774       540.34     50000.0
12177      354973  354973     3600.0    0.1862       131.28     60000.0
12178      355002  355002    15000.0    0.0881       475.68     62000.0
12179      355307  355307    15000.0    0.1774       540.34     54080.0

         dti  delinq_2yrs  inq_last_6mths  open_acc  ...  \
0      29.99          0.0             0.0      15.0  ...
1      11.26          2.0             0.0      16.0  ...
2      11.28          0.0             0.0      12.0  ...
3      18.08          0.0             0.0      12.0  ...
4      27.77          0.0             2.0      13.0  ...
...      ...          ...             ...       ...  ...
12175  28.42          0.0             0.0      15.0  ...
12176  23.43          4.0             0.0      16.0  ...
12177  28.80          0.0             1.0      14.0  ...
12178  11.44          0.0             0.0       5.0  ...
12179  21.66          1.0             1.0       5.0  ...

       verification_status_Verified  pymnt_plan_n  initial_list_status_f  \
0                                 0             1                      0
1                                 0             1                      0
2                                 0             1                      0
3                                 0             1                      0
4                                 0             1                      0
...                             ...           ...                    ...
12175                             0             1                      0
12176                             1             1                      0
12177                             0             1                      0
12178                             0             1                      0
12179                             0             1                      1

       initial_list_status_w  application_type_Individual  \
0                          1                            1
1                          1                            1
2                          1                            1
3                          1                            1
4                          1                            1
...                      ...                          ...
12175                      1                            1
12176                      1                            1
12177                      1                            1
12178                      1                            0
12179                      0                            1

       application_type_Joint App  hardship_flag_N  hardship_flag_Y  \
0                               0                1                0
1                               0                1                0
2                               0                1                0
3                               0                1                0
4                               0                1                0
...                           ...              ...              ...
12175                           0                1                0
12176                           0                1                0
12177                           0                1                0
12178                           1                1                0
12179                           0                1                0

       debt_settlement_flag_N  debt_settlement_flag_Y
0                           1                       0
1                           1                       0
2                           1                       0
3                           1                       0
4                           1                       0
...                       ...                     ...
12175                       1                       0
12176                       1                       0
12177                       1                       0
12178                       1                       0
12179                       1                       0

[12180 rows x 94 columns]
0        0
1        0
2        0
3        0
4        0
        ..
12175    1
12176    1
12177    1
12178    1
12179    1
Name: loan_status, Length: 12180, dtype: int64
      Unnamed: 0  index  loan_amnt  int_rate  installment  annual_inc    dti  \
0          67991  67991    40000.0    0.0819       814.70    140000.0  19.75
1          25429  25429     6000.0    0.1524       208.70     55000.0  11.52
2          38496  38496     3600.0    0.1695       128.27     42000.0   6.74
3          19667  19667    20000.0    0.1524       478.33    100000.0  12.13
4          37505  37505     3600.0    0.1240       120.27     50000.0  16.08
...          ...    ...        ...       ...          ...         ...    ...
4697       77282  77282    30000.0    0.1240       673.42    140480.0  15.74
4698       77291  77291    24000.0    0.0756       747.22     50000.0  26.81
4699       77292  77292    10000.0    0.2305       387.36     33000.0  38.51
4700       77297  77297     8000.0    0.1862       205.86     38000.0  16.36
4701       77304  77304    30000.0    0.2055      1123.34    180000.0  12.06

      delinq_2yrs  inq_last_6mths  open_acc  ...  \
0             0.0             1.0      18.0  ...
1             2.0             0.0       8.0  ...
2             0.0             0.0       6.0  ...
3             0.0             2.0       7.0  ...
4             0.0             3.0       6.0  ...
...           ...             ...       ...  ...
4697          0.0             0.0      20.0  ...
4698          0.0             0.0       9.0  ...
4699          0.0             2.0       7.0  ...
4700          0.0             1.0       8.0  ...
4701          0.0             0.0       8.0  ...

      verification_status_Verified  pymnt_plan_n  initial_list_status_f  \
0                                0             1                      0
1                                0             1                      0
2                                0             1                      0
3                                0             1                      0
4                                0             1                      0
...                            ...           ...                    ...
4697                             0             1                      1
4698                             0             1                      0
4699                             1             1                      1
4700                             0             1                      0
4701                             0             1                      1

      initial_list_status_w  application_type_Individual  \
0                         1                            1
1                         1                            1
2                         1                            1
3                         1                            1
4                         1                            1
...                     ...                          ...
4697                      0                            1
4698                      1                            1
4699                      0                            1
4700                      1                            1
4701                      0                            1

      application_type_Joint App  hardship_flag_N  hardship_flag_Y  \
0                              0                1                0
1                              0                1                0
2                              0                1                0
3                              0                1                0
4                              0                1                0
...                          ...              ...              ...
4697                           0                1                0
4698                           0                1                0
4699                           0                1                0
4700                           0                1                0
4701                           0                1                0

      debt_settlement_flag_N  debt_settlement_flag_Y
0                          1                       0
1                          1                       0
2                          1                       0
3                          1                       0
4                          1                       0
...                      ...                     ...
4697                       1                       0
4698                       1                       0
4699                       1                       0
4700                       1                       0
4701                       1                       0

[4702 rows x 94 columns]
0       0
1       0
2       0
3       0
4       0
       ..
4697    1
4698    1
4699    1
4700    1
4701    1
Name: loan_status, Length: 4702, dtype: int64

In [46]:
print(f"Train Shape:  {X_train.shape}, {y_train.shape}")
print(f"Test Shape:  {X_test.shape},{ y_test.shape}")

Train Shape:  (12180, 94), (12180,)
Test Shape:  (4702, 94),(4702,)

In [51]:
# Train the Logistic Regression model on the unscaled data and print the model score

modelLR= LogisticRegression(max_iter=2000)
modelLR.fit(X_train, y_train)

/Users/vasavdave/opt/anaconda3/envs/PythonAdv/lib/python3.6/site-packages/sklearn/linear_model/_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)

LogisticRegression(max_iter=2000)

In [52]:
print(f"Training Data Score (Logistic): {modelLR.score(X_train, y_train)}")
print(f"Testing Data Score (Logistic): {modelLR.score(X_test, y_test)}")

Training Data Score (Logistic): 0.6972085385878489
Testing Data Score (Logistic): 0.5716716290940026

In [53]:
# Train a Random Forest Classifier model and print the model score

modelRFC = RandomForestClassifier(random_state=1, n_estimators=1000)
modelRFC.fit(X_train, y_train)

RandomForestClassifier(n_estimators=1000, random_state=1)

In [54]:
print(f"Training Data Score (RandomForest): {modelRFC.score(X_train, y_train)}")
print(f"Testing Data Score (RandomForest): {modelRFC.score(X_test, y_test)}")

Training Data Score (RandomForest): 1.0
Testing Data Score (RandomForest): 0.6061250531688643

In [56]:
# Scale the data
scaler = StandardScaler().fit(X_train)

X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [57]:
# Train the Logistic Regression model on the scaled data and print the model score
modelLRS = LogisticRegression(max_iter=2000)
modelLRS.fit(X_train_scaled, y_train)

print(f"Training Data Score (Scaled Logistic): {modelLRS.score(X_train_scaled, y_train)}")
print(f"Testing Data Score (Scaled Logistic): {modelLRS.score(X_test_scaled, y_test)}")

Training Data Score (Scaled Logistic): 0.7127257799671592
Testing Data Score (Scaled Logistic): 0.7201190982560612

In [58]:
# Train a Random Forest Classifier model on the scaled data and print the model score
modelRFC = RandomForestClassifier(random_state=1, n_estimators=1000)
modelRFC.fit(X_train_scaled, y_train)

print(f"Training Data Score (Scaled RandomForest): {modelRFC.score(X_train_scaled, y_train)}")
print(f"Testing Data Score (Scaled RandomForest): {modelRFC.score(X_test_scaled, y_test)}")

Training Data Score (Scaled RandomForest): 1.0
Testing Data Score (Scaled RandomForest): 0.6069757549978733

In [63]:
print(f"Training Data Score (Unscaled Logistic): {modelLR.score(X_train, y_train)}")
print(f"Testing Data Score (Unscaled Logistic): {modelLR.score(X_test, y_test)}")
print(f"-----")
print(f"Training Data Score (Scaled Logistic): {modelLRS.score(X_train_scaled, y_train)}")
print(f"Testing Data Score (Scaled Logistic): {modelLRS.score(X_test_scaled, y_test)}")
print(f"-----")
print(f"Training Data Score (Unscaled RandomForest): {modelRFC.score(X_train, y_train)}")
print(f"Testing Data Score (Unscaled RandomForest): {modelRFC.score(X_test, y_test)}")
print(f"-----")
print(f"Training Data Score (Scaled RandomForest): {modelRFC.score(X_train_scaled, y_train)}")
print(f"Testing Data Score (Scaled RandomForest): {modelRFC.score(X_test_scaled, y_test)}")

Training Data Score (Unscaled Logistic): 0.6972085385878489
Testing Data Score (Unscaled Logistic): 0.5716716290940026
-----
Training Data Score (Scaled Logistic): 0.7127257799671592
Testing Data Score (Scaled Logistic): 0.7201190982560612
-----
Training Data Score (Unscaled RandomForest): 0.49712643678160917
Testing Data Score (Unscaled RandomForest): 0.4293917481922586
-----
Training Data Score (Scaled RandomForest): 1.0
Testing Data Score (Scaled RandomForest): 0.6069757549978733

# Conclusion:

Prediction was incorrect. Logistic Regression performed better than Random forest. Random forest was not an apt model for this dataset. Random forest model was over fitting based on testing annd training score achieved, before and after scaling. Whereas in Logistic Regression scores were much closer to each other.